/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AccessToken {
  created_at: Generated<number>;
  expires: string;
  public_key: string;
  session_id: string;
  uuid: string;
}

export interface Auth {
  created_at: Generated<number>;
  fp_hash: Generated<string>;
  id: string;
  locked_until: Generated<string | null>;
  login_fail_count: Generated<number>;
  password: string;
  uuid: string;
}

export interface EventRate {
  buried_treasure: Generated<number>;
  earthquake: Generated<number>;
  eruption: Generated<number>;
  fall_down: Generated<number>;
  fire: Generated<number>;
  huge_meteorite: Generated<number>;
  meteorite: Generated<number>;
  monster: Generated<number>;
  oil_exhaustion: Generated<number>;
  oil_field: Generated<number>;
  propaganda: Generated<number>;
  tsunami: Generated<number>;
  typhoon: Generated<number>;
  uuid: string;
}

export interface Island {
  area: number;
  factory: number;
  farm: number;
  food: number;
  island_info: string;
  mining: number;
  missile: number;
  money: number;
  population: number;
  prize: string;
  uuid: string;
}

export interface LastLogin {
  consecutive_login_days: Generated<number>;
  last_bonus_received_at: Generated<number>;
  last_login_at: Generated<number>;
  uuid: string;
}

export interface Passkey {
  counter: Generated<number>;
  created_at: Generated<number>;
  credential_id: string;
  device_name: string;
  fp_hash: Generated<string>;
  public_key: string;
  uuid: string;
}

export interface Plan {
  from_uuid: string;
  plan: string;
  plan_no: number;
  times: number;
  to_uuid: string;
  x: number;
  y: number;
}

export interface RefreshToken {
  created_at: Generated<number>;
  expires: string;
  public_key: string;
  session_id: string;
  uuid: string;
}

export interface Role {
  role: Generated<number>;
  uuid: string;
}

export interface TurnLog {
  from_uuid: string;
  log: string | null;
  log_uuid: string;
  secret_log: string;
  to_uuid: string | null;
  turn: number;
}

export interface TurnState {
  last_updated_at: Generated<number>;
  turn: Generated<number>;
  turn_processing: Generated<number>;
}

export interface User {
  inhabited: Generated<number>;
  island_name: string;
  user_name: string;
  uuid: string;
}

export interface DB {
  access_token: AccessToken;
  auth: Auth;
  event_rate: EventRate;
  island: Island;
  last_login: LastLogin;
  passkey: Passkey;
  plan: Plan;
  refresh_token: RefreshToken;
  role: Role;
  turn_log: TurnLog;
  turn_state: TurnState;
  user: User;
}
